name: project-71-check
run-name: ${{ github.actor }}

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Java JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '20'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
  coverage:
    needs: [build]
    name: Test Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Java JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '20'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Test code coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_I }}
        with:
          coverageCommand: gradle test